#!/bin/bash

JAVA8_PKG=
ES_HOME=
ES_BIN=$ES_HOME/bin/elasticsearch
ES_CONFIG=$ES_HOME/config/elasticsearch.yml


#JAVA8
if ["8" != $(javac -version 2>&1 | awk '{print $2}' | awk -F '.' '{print $2}')]
then
	java8Pkg $JAVA8_PKG
	java8Guide $ES_BIN
fi


#add es user
useradd -d /home/es -m es
echo "es.123" | passwd --stdin es
chown -R es:es $ES_HOME


#yml
hostNode=$(echo $THIS_HOST)
allNodes=
./es_yml -hostNode=hostNode -allNodes=allNodes
mv elasticsearch.yml $ES_CONFIG -f


#max number of threads
if ["" = $(cat /etc/security/limits.conf | sed -n '/es soft nproc 4096/p')]
then
	sed -i '$a es soft nproc 4096\es hard nproc 4096' /etc/security/limits.conf
fi


#max virtual memory
if ["" = $(cat /etc/sysctl.conf | sed -n '/vm.max_map_count/p')]
then
	echo "vm.max_map_count=262144" >> /etc/sysctl.conf
else
	sed -i 's/vm.max_map_count=.*/vm.max_map_count=262144/'
fi


#max file descriptors
if ["" = $(nl /etc/security/limits.conf | sed -n '/es hard nofile 65536/p')]
then
	sed -i '$a es hard nofile 65536\es soft nofile 65536' /etc/security/limits.conf
fi

#memory locking
if ["" = $(nl /etc/security/limits.conf | sed -n '/es soft memlock unlimited/p')]
then
	sed -i '$a es soft memlock unlimited\es hard memlock unlimited' /etc/security/limits.conf
fi


#run es
su es
$ES_BIN/elasticsearch



java8Guide(){
	if ["" = $(cat $1 | sed -n '/JAVA_HOME/p')]
	then
		sed -i '1i export JAVA_HOME=/opt/tool/jdk \
		export PATH=$JAVA_HOME/bin:$PATH \
		export CLASSPATH=.:$JAVA_HOME/lib.dt.jar:$JAVA_HOME/lib/tools.jar \
		export JRE_HOME=$JAVA_HOME/jre' $1
	fi
}

java8Pkg(){
	tar zxvf $1 -C /opt/tool
	mv $(ls | sed '/jdk.*/p') jdk
}





