#!/bin/bash

ES_NODES=
HOME=es_click_once/es_model

OLD_IFS="$IFS" 
IFS=","

arr=($ES_NODES) 

IFS="$OLD_IFS" 

success=false

for host in ${arr[@]} 
do 
    if ["" != $(curl -XPUT 'host:9200/apt' --data-binary @$HOME/es_model | sed -n '/.*acknowledged.*true.*shards_acknowledged.*true/p')]
	then
		success=true
		break
done

echo $success