#!/bin/bash

conf=conf.ini

partitionSet=0,1,2,3

nodes=192.168.1.103,192.168.1.102
port=9200

echo " " > $conf

sed -i '1i [topic] \
vds-alert = '$partitionSet' \
waf-alert = '$partitionSet' \
ids-alert = '$partitionSet' \
\
[kafka] \
brokers = '$kafka-brokers' \
start = \
\
[elasticsearch] \
nodes = '$nodes' \
port = '$port'' $conf

