#!/bin/bash
#
# chkconfig: 23456 91 91
# description: ES 
# processname: es 
#
. /etc/profile

log=/var/log/es-$(date +'%Y%m%d')
function start() {
	local pid=$(ps aux | grep java | grep elasticsearch | awk '{print $2}')	
	if [ -n "$pid" ];then
		return 0
	fi
	su - es -c "exec ${Apthome}/package/${App}/elasticsearch-5.2.2/bin/elasticsearch" 2>$log &
        local pid=$(ps aux | grep /bin/elasticsearch | grep -v grep | awk '{print $2}')
	echo ${pid} > ${APT_PID_FILE}/${App}.pid
}

function stop() {
	kill `cat /var/run/${App}.pid`	
}


Apthome=${APT_HOME}
App="es"
case $1 in
  "start")
  start
  ;;
  "stop")
  stop
  ;;
  "restart")
  ;;
esac

exit 0
